[DOCUMENTATION]
ORG_NAME="Elton Aldroiks Value Developer"
ORG_DBA="YulAldr"
ORG_URL="https://yulaldr.github.io/StellarEU/index.html"
ORG_LOGO="https://yulaldr.github.io/StellarEU/StellarEU.png"
ORG_DESCRIPTION="Smarts solutions for your investment"
ORG_OFFICIAL_EMAIL="yulongaldroiks@gmail.com"
[[PRINCIPALS]]
name="Yulong Aldroiks"
email="yulongaldroiks@gmail.com"
twitter="@YulAldr"
[[CURRENCIES]]
code="StellarEU"
issuer="GALN76JFY2ROUGZB2P4YRYFAHZTBUF4ZKSJ7ENUTG7CJNFFUNG6KYFUL"
display_decimals=7
name="StellarEU Token"
desc="Token was made by Elton Aldroiks Value Developer . StellarEU is an utility token to store and move value with almost no fee for the secure and fast transaction. StellarEU is a token of the blockchain stellar.org and can be bought with the native cryptocurrency XLM in the exchange of the Stellar Development Fondation "
